### PR TITLE
add new template events

### PR DESCRIPTION
**Pull request by alg5**
@lavigor, @Tatiana5,  these are 3 new template events

### CODE REVIEW

**Comment by lavigor** [comment]
Please change `smyle` to `smiley` (as in the original).
Then I'll merge the PR.

**Comment by alg5** [comment]
done

**Comment by lavigor** [comment]
OK. Thank you!

**Comment by Galixte** [comment]
Hi @alg5,

it’s for one of your extension ?

**Comment by alg5** [comment]
hi @Galixte , no sure, it was  my pull request

**Pull request merged**
